# ============================================================
# Dockerfile — Multi-stage build for LunchPrep (Next.js)
# Base image: node:20-alpine (small, production-ready)
#
# Stages:
#   1. deps    — install all npm dependencies
#   2. builder — build the Next.js standalone production bundle
#   3. runner  — minimal runtime image (~150 MB) with non-root user
#
# Usage:
#   Build:  docker build -t lunchprep .
#   Run:    docker run -p 3000:3000 -e GEMINI_API_KEY=<key> lunchprep
#
# Environment variables (all passed at runtime, NOT build time):
#   GEMINI_API_KEY  — Required for hosted mode (server-side Gemini proxy)
#   GEMINI_MODEL    — Optional; defaults to gemini-2.5-flash-lite
#   RATE_LIMIT_RPM  — Optional; defaults to 10 requests/min per IP
# ============================================================

# ---- Stage 1: Install dependencies ----
FROM node:20-alpine AS deps

# Reason: libc6-compat provides glibc compatibility shims needed by some
# native npm packages on Alpine (musl libc).
RUN apk add --no-cache libc6-compat

WORKDIR /app

# Copy lockfile and manifest first to maximise Docker layer caching.
# Only re-runs npm ci when package.json or package-lock.json change.
COPY package.json package-lock.json ./

RUN npm ci

# ---- Stage 2: Build the Next.js application ----
FROM node:20-alpine AS builder

WORKDIR /app

# Copy installed node_modules from deps stage
COPY --from=deps /app/node_modules ./node_modules

# Copy the rest of the application source
COPY . .

# Reason: Disabling telemetry prevents outbound calls to Vercel during build.
ENV NEXT_TELEMETRY_DISABLED=1
ENV NODE_ENV=production

# Produces .next/standalone/ (self-contained server) and .next/static/ (assets)
RUN npm run build

# ---- Stage 3: Minimal production runtime ----
FROM node:20-alpine AS runner

WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1

# Reason: HOSTNAME=0.0.0.0 is required for Google Cloud Run — the container
# must listen on all interfaces, not just localhost, for health checks to pass.
ENV HOSTNAME="0.0.0.0"
ENV PORT=3000

# Create a non-root system user for security best practices
RUN addgroup --system --gid 1001 nodejs && \
    adduser --system --uid 1001 nextjs

# public/ — static assets (not included in the standalone bundle)
COPY --from=builder --chown=nextjs:nodejs /app/public ./public

# .next/standalone/ — the self-contained Node.js server with bundled deps
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./

# .next/static/ — compiled JS chunks and CSS (served from /app/.next/static)
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

# Drop to non-root user before starting the server
USER nextjs

EXPOSE 3000

# server.js is the standalone entry point generated by `next build`
CMD ["node", "server.js"]
